### ISSUE TITLE
Cant delete directories

### ISSUE THREAD

**Issue by fabien007** [BunnyWay/BunnyCDN.PHP.Storage#10]
The `delete `and `deleteMultiple `function use `normalizePath `with `$isDirectory` set to `false`.
So its impossible to delete directory with this API.

A simple solution is to set `$isDirectory` with `str_ends_with($path, '/')`.

line 54 become : 
`$response = $this->httpClient->request('DELETE', $this->normalizePath($path, str_ends_with($path, '/')));`
line 202 become :
`$requests[$path] = $this->httpClient->requestAsync('DELETE', $this->normalizePath($path, str_ends_with($path, '/')));`

**Comment by rafael-at-bunny** [comment]
Hi.

Thank you for your report.

A fix has been provided with aac19e13ed091e6dca25ca2df8ebebfe2e29873d, which should get tagged in the next major/minor release (2.2/3.0). The next release is not scheduled yet.

Thank you.
