### ISSUE TITLE
client->delete() returns object not found

### ISSUE THREAD

**Issue by mkinternet** [BunnyWay/BunnyCDN.PHP.Storage#11]
client->delete() returns 

Could not find part of the object path: Object Not Found

Object exists in storage.

Tested with path starting with '/' or not.

Worked with version 2.0.0

**Comment by rafael-at-bunny** [comment]
This library only wraps the Bunny API, so this might be an issue in the underlying storage.

If you're still having this issue, please contact [Bunny Support](https://support.bunny.net/).

**Comment by mkinternet** [comment]
Isn't it official bunny.net PHP api library? Why do you forward me to bunny support.
