### ISSUE TITLE
Replace guzzle with psr7 adapter and any client

### ISSUE THREAD

**Issue by tacman** [BunnyWay/BunnyCDN.PHP.Storage#14]
I'd like to use the Symfony HttpClient rather than Guzzle.  And others may want to use something else from this list https://packagist.org/providers/psr/http-client-implementation

To do that, we'd change the instructions and code to install the adapter at the same time.

```bash
composer require guzzlehttp/guzzle http-interop/http-factory-guzzle:^1.0
```

Here is an example of installation with the `symfony/http-client`:

```bash
composer require symfony/http-client nyholm/psr7:^1.0
```

I _think_ then you'd change the client code and replace Guzzle with the generic interface.

```php

    public function __construct(
        string $apiKey,
        string $storageZoneName,
        string $storageZoneRegion = Region::FALKENSTEIN,
       ?HttpClientInterface $httpClient = null
```

The problem is that right now I can't even pass it my own client, as it has to a Guzzle Client.  It might be as simple as changing the signature to

\Psr\Http\Client\ClientInterface (which Guzzle implements) or the Symfony Cache contracts.  

The Symfony client integrates seamlessly with the debug toolbar.  Plus, I don't want to download Guzzle in my app just for the library.

Thanks for your consideration.

**Comment by rafael-at-bunny** [comment]
I haven't had the time to look into this yet, but in the case that you might have seen it already, is there a way to handle sync/async calls with the PSR interface? Seems like Guzzle [forces](https://github.com/guzzle/guzzle/blob/7.8/src/Client.php#L134) `sendRequest` to be synchronous, so I _guess_ there isn't a PSR-18 compatible way of doing so?

**Comment by tacman** [comment]
I'm not quite sure.  But Toshy gave me a nice explanation at https://github.com/ToshY/BunnyNet-PHP/issues/121

I also realized that his package does support storage, so I'll probably just use that, since it appears to be a super-set of this library.
