### ISSUE TITLE
Bytes aren't calculated properly until PHP is done executing (due to curl+streams)

### ISSUE THREAD

**Issue by mike503** [BunnyWay/BunnyCDN.PHP.Storage#5]
Due to passing a stream to curl for CURLOPT_INFILE and CURLOPT_FILE, functions get back 0 bytes or believe something is 0 bytes.

This can be worked around by forcing a clearstatcache(), but there might be a better way to handle things instead of opening a stream and never closing it. Specifically downloadFile and uploadFile.

For example in downloadFile, $dataLength = filesize($localPath); returns 0 bytes. It's not used at all, so it's really just cruft, but I am trying to create a function to "copy" a file from one location to another (like copyObject in S3) which relies on the a file being downloaded to temp space, then uploaded. However, the downloaded file is stat cached at 0 bytes.

Basically it's the equivalent of this pseudocode, which DOESN'T WORK:

```php
$temp = tempnam();
if (downloadFile("object", $temp)) {
  if (uploadFile($temp, "newobject")) {
   // success!
  }
}
```

This does, apprently, thanks to that clearstatcache(). There's gotta be a way in-process to not have cached data. I'm assuming PHP is only caching the stat data due to it using fopen/streams, and then filesize() returns 0.

```php
$temp = tempnam();
if (downloadFile("object", $temp)) {
  clearstatcache();
  if (uploadFile($temp, "newobject")) {
   // success!
  }
}
```

The issue is, uploadFile($temp...) winds up seeing $temp as a 0 byte file. Issuing a clearstatcache() in between does reset PHP's knowledge of this, but it could be done inside of the SDK. It also doesn't seem to simply "clear" by closing out the stream. I'm not sure if there's any better/more efficient way to handle things instead of passing around file streams instead of simply telling curl (or possibly guzzle?) "hey, just download $foo to $bar" and not have to open a stream to pass it into.

Just wanted to log this as an issue, there's a (hokey) workaround for it for now.

**Comment by rafael-at-bunny** [comment]
Hi.

Thank you for documenting this. We added Guzzle to the 2.1.0 version, so this should be less painful now.

Thank you.
