### ISSUE TITLE
sendHttpRequest has wrong return type, bool (true) returned, but string expected.

### ISSUE THREAD

**Issue by dcoding1** [BunnyWay/BunnyCDN.PHP.Storage#9]
https://github.com/BunnyWay/BunnyCDN.PHP.Storage/blob/4f57caf033bca2255c1d75d369061902e2a32da5/src/Client.php#L131C24-L131C24

**Comment by rafael-at-bunny** [comment]
This has been addressed in the [2.1.0 release](https://github.com/BunnyWay/BunnyCDN.PHP.Storage/releases/tag/2.1.0). Thank you.
